### ISSUE TITLE
This project is copied from my Github

### ISSUE THREAD

**Issue by charlie60507** [amirdeljouyi/Genetic-Algorithm-on-K-Means-Clustering#4]
Your implementation is copied from my Github which was upload 4 years ago (https://github.com/charlie60507/Genetic-Kmeans-Algorithm-GKA-)
Although you have refactor the code, it is easy to find the similarities (like coding style, code flow, comment, etc.) 
The most obvious evidence is you removed my test data (https://reurl.cc/x0XX8L) which was put in this folder (https://reurl.cc/14zzWV) 
Perhaps you can mark it is referenced to my work instead of copying and pasting to your Github without any ask to me

BRs, Charlie Yang

**Comment by amirdeljouyi** [comment]
Dear @charlie60507, 

I apologize for not referencing your work and for any inconvenience caused. So I have referenced your work in this project. However, there are big differences between this repository and your repository (like fitness function, normalization, etc.).

Please accept my sincere apology.
Amirhossein Deljouyi
